<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Account 的列表
 *
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.Accounts</code>
 */
class Accounts extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.Account acc = 1;</code>
     */
    private $acc;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\Account[]|\Google\Protobuf\Internal\RepeatedField $acc
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.Account acc = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAcc()
    {
        return $this->acc;
    }

    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.Account acc = 1;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\Account[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAcc($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Chain33\Phpsdk\Lib\Protobuf\Types\Account::class);
        $this->acc = $arr;

        return $this;
    }

}

