<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coins.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * message for execs.coins
 *
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.CoinsAction</code>
 */
class CoinsAction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 ty = 3;</code>
     */
    private $ty = 0;
    protected $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransfer $transfer
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsWithdraw $withdraw
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsGenesis $genesis
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransferToExec $transferToExec
     *     @type int $ty
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Coins::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsTransfer transfer = 1;</code>
     * @return \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransfer
     */
    public function getTransfer()
    {
        return $this->readOneof(1);
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsTransfer transfer = 1;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransfer $var
     * @return $this
     */
    public function setTransfer($var)
    {
        GPBUtil::checkMessage($var, \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransfer::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsWithdraw withdraw = 4;</code>
     * @return \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsWithdraw
     */
    public function getWithdraw()
    {
        return $this->readOneof(4);
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsWithdraw withdraw = 4;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsWithdraw $var
     * @return $this
     */
    public function setWithdraw($var)
    {
        GPBUtil::checkMessage($var, \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsWithdraw::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsGenesis genesis = 2;</code>
     * @return \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsGenesis
     */
    public function getGenesis()
    {
        return $this->readOneof(2);
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsGenesis genesis = 2;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsGenesis $var
     * @return $this
     */
    public function setGenesis($var)
    {
        GPBUtil::checkMessage($var, \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsGenesis::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsTransferToExec transferToExec = 5;</code>
     * @return \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransferToExec
     */
    public function getTransferToExec()
    {
        return $this->readOneof(5);
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.AssetsTransferToExec transferToExec = 5;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransferToExec $var
     * @return $this
     */
    public function setTransferToExec($var)
    {
        GPBUtil::checkMessage($var, \Chain33\Phpsdk\Lib\Protobuf\Types\AssetsTransferToExec::class);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 ty = 3;</code>
     * @return int
     */
    public function getTy()
    {
        return $this->ty;
    }

    /**
     * Generated from protobuf field <code>int32 ty = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTy($var)
    {
        GPBUtil::checkInt32($var);
        $this->ty = $var;

        return $this;
    }

    /**
     * @return string
     */
    public function getValue()
    {
        return $this->whichOneof("value");
    }

}

