<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.ExecAccount</code>
 */
class ExecAccount extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string execer = 1;</code>
     */
    private $execer = '';
    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account account = 2;</code>
     */
    private $account = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $execer
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\Account $account
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string execer = 1;</code>
     * @return string
     */
    public function getExecer()
    {
        return $this->execer;
    }

    /**
     * Generated from protobuf field <code>string execer = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setExecer($var)
    {
        GPBUtil::checkString($var, True);
        $this->execer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account account = 2;</code>
     * @return \Chain33\Phpsdk\Lib\Protobuf\Types\Account
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account account = 2;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\Account $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkMessage($var, \Chain33\Phpsdk\Lib\Protobuf\Types\Account::class);
        $this->account = $var;

        return $this;
    }

}

