<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.ReceiptAccountBurn</code>
 */
class ReceiptAccountBurn extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account prev = 1;</code>
     */
    private $prev = null;
    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account current = 2;</code>
     */
    private $current = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\Account $prev
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\Account $current
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Account::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account prev = 1;</code>
     * @return \Chain33\Phpsdk\Lib\Protobuf\Types\Account
     */
    public function getPrev()
    {
        return $this->prev;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account prev = 1;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\Account $var
     * @return $this
     */
    public function setPrev($var)
    {
        GPBUtil::checkMessage($var, \Chain33\Phpsdk\Lib\Protobuf\Types\Account::class);
        $this->prev = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account current = 2;</code>
     * @return \Chain33\Phpsdk\Lib\Protobuf\Types\Account
     */
    public function getCurrent()
    {
        return $this->current;
    }

    /**
     * Generated from protobuf field <code>.chain33.phpsdk.lib.protobuf.types.Account current = 2;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\Account $var
     * @return $this
     */
    public function setCurrent($var)
    {
        GPBUtil::checkMessage($var, \Chain33\Phpsdk\Lib\Protobuf\Types\Account::class);
        $this->current = $var;

        return $this;
    }

}

