<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.Reply</code>
 */
class Reply extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isOk = 1;</code>
     */
    private $isOk = false;
    /**
     * Generated from protobuf field <code>bytes msg = 2;</code>
     */
    private $msg = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isOk
     *     @type string $msg
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isOk = 1;</code>
     * @return bool
     */
    public function getIsOk()
    {
        return $this->isOk;
    }

    /**
     * Generated from protobuf field <code>bool isOk = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsOk($var)
    {
        GPBUtil::checkBool($var);
        $this->isOk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes msg = 2;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     * Generated from protobuf field <code>bytes msg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, False);
        $this->msg = $var;

        return $this;
    }

}

