<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.ReplyTxInfos</code>
 */
class ReplyTxInfos extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.ReplyTxInfo txInfos = 1;</code>
     */
    private $txInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\ReplyTxInfo[]|\Google\Protobuf\Internal\RepeatedField $txInfos
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.ReplyTxInfo txInfos = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTxInfos()
    {
        return $this->txInfos;
    }

    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.ReplyTxInfo txInfos = 1;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\ReplyTxInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTxInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Chain33\Phpsdk\Lib\Protobuf\Types\ReplyTxInfo::class);
        $this->txInfos = $arr;

        return $this;
    }

}

