<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.ReplyStrings</code>
 */
class ReplyStrings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string datas = 1;</code>
     */
    private $datas;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $datas
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string datas = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDatas()
    {
        return $this->datas;
    }

    /**
     * Generated from protobuf field <code>repeated string datas = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDatas($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->datas = $arr;

        return $this;
    }

}

