<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.ReqGetMempool</code>
 */
class ReqGetMempool extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool isAll = 1;</code>
     */
    private $isAll = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $isAll
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool isAll = 1;</code>
     * @return bool
     */
    public function getIsAll()
    {
        return $this->isAll;
    }

    /**
     * Generated from protobuf field <code>bool isAll = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAll($var)
    {
        GPBUtil::checkBool($var);
        $this->isAll = $var;

        return $this;
    }

}

