<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.ReWriteRawTx</code>
 */
class ReWriteRawTx extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tx = 1;</code>
     */
    private $tx = '';
    /**
     * bytes  execer = 2;
     *
     * Generated from protobuf field <code>string to = 3;</code>
     */
    private $to = '';
    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     */
    private $expire = '';
    /**
     * Generated from protobuf field <code>int64 fee = 5;</code>
     */
    private $fee = 0;
    /**
     * Generated from protobuf field <code>int32 index = 6;</code>
     */
    private $index = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tx
     *     @type string $to
     *           bytes  execer = 2;
     *     @type string $expire
     *     @type int|string $fee
     *     @type int $index
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tx = 1;</code>
     * @return string
     */
    public function getTx()
    {
        return $this->tx;
    }

    /**
     * Generated from protobuf field <code>string tx = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTx($var)
    {
        GPBUtil::checkString($var, True);
        $this->tx = $var;

        return $this;
    }

    /**
     * bytes  execer = 2;
     *
     * Generated from protobuf field <code>string to = 3;</code>
     * @return string
     */
    public function getTo()
    {
        return $this->to;
    }

    /**
     * bytes  execer = 2;
     *
     * Generated from protobuf field <code>string to = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTo($var)
    {
        GPBUtil::checkString($var, True);
        $this->to = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     * @return string
     */
    public function getExpire()
    {
        return $this->expire;
    }

    /**
     * Generated from protobuf field <code>string expire = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setExpire($var)
    {
        GPBUtil::checkString($var, True);
        $this->expire = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 fee = 5;</code>
     * @return int|string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>int64 fee = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 index = 6;</code>
     * @return int
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>int32 index = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setIndex($var)
    {
        GPBUtil::checkInt32($var);
        $this->index = $var;

        return $this;
    }

}

