<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * 环签名类型时，签名字段存储的环签名信息
 *
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.RingSignature</code>
 */
class RingSignature extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.RingSignatureItem items = 1;</code>
     */
    private $items;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Chain33\Phpsdk\Lib\Protobuf\Types\RingSignatureItem[]|\Google\Protobuf\Internal\RepeatedField $items
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Transaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.RingSignatureItem items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->items;
    }

    /**
     * Generated from protobuf field <code>repeated .chain33.phpsdk.lib.protobuf.types.RingSignatureItem items = 1;</code>
     * @param \Chain33\Phpsdk\Lib\Protobuf\Types\RingSignatureItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Chain33\Phpsdk\Lib\Protobuf\Types\RingSignatureItem::class);
        $this->items = $arr;

        return $this;
    }

}

