<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.TimeStatus</code>
 */
class TimeStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ntpTime = 1;</code>
     */
    private $ntpTime = '';
    /**
     * Generated from protobuf field <code>string localTime = 2;</code>
     */
    private $localTime = '';
    /**
     * Generated from protobuf field <code>int64 diff = 3;</code>
     */
    private $diff = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ntpTime
     *     @type string $localTime
     *     @type int|string $diff
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ntpTime = 1;</code>
     * @return string
     */
    public function getNtpTime()
    {
        return $this->ntpTime;
    }

    /**
     * Generated from protobuf field <code>string ntpTime = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNtpTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->ntpTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string localTime = 2;</code>
     * @return string
     */
    public function getLocalTime()
    {
        return $this->localTime;
    }

    /**
     * Generated from protobuf field <code>string localTime = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLocalTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->localTime = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 diff = 3;</code>
     * @return int|string
     */
    public function getDiff()
    {
        return $this->diff;
    }

    /**
     * Generated from protobuf field <code>int64 diff = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDiff($var)
    {
        GPBUtil::checkInt64($var);
        $this->diff = $var;

        return $this;
    }

}

