<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic.proto

namespace Chain33\Phpsdk\Lib\Protobuf\Types;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\Internal\GPBWrapperUtils;

/**
 *手续费
 *
 * Generated from protobuf message <code>chain33.phpsdk.lib.protobuf.types.TotalFee</code>
 */
class TotalFee extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 fee = 1;</code>
     */
    private $fee = 0;
    /**
     * Generated from protobuf field <code>int64 txCount = 2;</code>
     */
    private $txCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $fee
     *     @type int|string $txCount
     * }
     */
    public function __construct($data = NULL) {
        \chain33\phpsdk\lib\protobuf\Statistic::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 fee = 1;</code>
     * @return int|string
     */
    public function getFee()
    {
        return $this->fee;
    }

    /**
     * Generated from protobuf field <code>int64 fee = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setFee($var)
    {
        GPBUtil::checkInt64($var);
        $this->fee = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 2;</code>
     * @return int|string
     */
    public function getTxCount()
    {
        return $this->txCount;
    }

    /**
     * Generated from protobuf field <code>int64 txCount = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxCount($var)
    {
        GPBUtil::checkInt64($var);
        $this->txCount = $var;

        return $this;
    }

}

